# Generated by Django 2.2.6 on 2019-10-28 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('summary', models.TextField()),
                ('status', models.CharField(max_length=64)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('tenure', models.IntegerField()),
                ('rate_of_return', models.CharField(max_length=32)),
                ('image_top_name', models.CharField(default='images/des_moines.png', max_length=255)),
                ('minimum_investment', models.IntegerField(default=10000)),
                ('project_address', models.CharField(max_length=255)),
                ('financials', models.TextField()),
                ('investors', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('committed_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('time_stamp', models.DateTimeField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='showme.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(max_length=16)),
                ('committed_amount', models.FloatField(default=0)),
                ('kyc_complete', models.BooleanField()),
                ('investor_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
